# 02 - Pandas - Series

In [99]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" PANDAS VERSIÓN")
print(pd.__version__) # imprime versión de pandas (sólo números)

=============== PANDAS VERSIÓN
2.3.3

# 2.1 SERIES: Constructor (parámetros del constructor)

### Constructor: pd.Series()

`pd.Series([data, index, dtype, name, copy])`

### 2.1.1 data = UN ARRAY  

```
serie21 = pd.Series([0,1,2,3,4,5])
print(serie21)
```

### 2.1.2 index = UN ARRAY  

`serie21 = pd.Series([0,1,2,3,4,5], index=['a','b','c','d','e','f'])`

### 2.1.3 dtype = Tipo de dato

`serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], dtype=np.int8)`

### 2.1.4 name="un string"

`serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], name='Mi Serie')`

### 2.1.5 copy = Booleano

*copy=True si se debe realizar una copia de los datos en lugar de crear una referencia*

## RECORDAR: Series no tiene Display

In [100]:
# CÓDIGO DE LA SECCIÓN 2.1 SERIES: Constructor

print(f'\n{"="*15} 2.1 SERIES: Constructor')

print("\nA) Imprime una serie con índice por defecto (0,1,2,3,4,5)")
serie21 = pd.Series(data = [0,1,2,3,4,5])
print(serie21) # Imprime una serie con índice por defecto (0,1,2,3,4,5)

print("\nB) Imprime una serie con índice personalizado ('a','b','c','d','e','f')")
serie21 = pd.Series([0,1,2,3,4,5], index=['a','b','c','d','e','f'])
print(serie21) # Imprime una serie con índice personalizado ('a','b','c','d','e','f')

print("\nC) Imprime el Tipo de dato (personalizado) de una serie (np.int8)")
serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], dtype=np.int8)
print(serie21) # imprime la serie con índice numérico
print(f'Tipo de dato de la serie: {serie21.dtype}') # Imprime el Tipo de dato (personalizado) de una serie (np.int8)

print("\nD) Imprime el nombre personalizado de una serie")
serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], name='Mi Serie')
print(f'Nombre de la serie: {serie21.name}') # Imprime el nombre personalizado de una serie

print("\nE) Imprime una serie creada a partir de un diccionario")
serie21 = pd.Series({'a':0,'b':1,'c':2,'d':3,'e':4,'f':5})
print(serie21) # Imprime una serie creada a partir de un diccionario

print("\nF) Imprime una serie creada a partir de un array de NumPy")
serie211 = pd.Series(np.array([0,1,2,3,4,5]))
print(serie21) # Imprime una serie creada a partir de un array de NumPy
print(f'Tipo de dato de la serie creada a partir de un array de NumPy: {serie21.dtype}') # Imprime el tipo de dato de la serie

print("\nG) Imprime una serie con un valor escalar repetido: el número 5")
serie21 = pd.Series(5, index=['a','b','c','d','e','f']) # o data=5
print(serie21) # imprime una serie con valor escalar repetido: el número 5

print("\nH) copy=True si se debe realizar una copia de los datos en lugar de crear una referencia")
serie21 = pd.Series(copy=True) # True si se debe realizar una copia de los datos en lugar de crear una referencia

=============== 2.1 SERIES: Constructor

A) Imprime una serie con índice por defecto (0,1,2,3,4,5)
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

B) Imprime una serie con índice personalizado ('a','b','c','d','e','f')
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

C) Imprime el Tipo de dato (personalizado) de una serie (np.int8)
10    0
11    1
12    2
13    3
14    4
15    5
dtype: int8
Tipo de dato de la serie: int8

D) Imprime el nombre personalizado de una serie
Nombre de la serie: Mi Serie

E) Imprime una serie creada a partir de un diccionario
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

F) Imprime una serie creada a partir de un array de NumPy
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64
Tipo de dato de la serie creada a partir de un array de NumPy: int64

G) Imprime una serie con un valor escalar repetido: el número 5
a    5
b    5
c    5
d    5
e    5
f    5
dtype: int64

H) copy=True si se debe realizar una copia de los datos en lugar de crear una referencia

# 2.2 Series: Atributos

`serie22 = pd.Series(data=[0,1,2,3,4])`

2.2.1 Atributo index:  
`print(serie22.index)  # RangeIndex(start=0, stop=5, step=1)`

2.2.2 Atributo dtype: tipo del contenido de la serie  
`print(serie22.dtype)  # int64`

2.2.3 Atributo size: tamaño  
`print(serie22.size)   # 5`

2.2.4 Atributo ndim: dimensiones  
`print(serie22.ndim)   # 1`

2.2.5 Atributo values: valores del array  
`print(serie22.values) # [0 1 2 3 4]`

2.2.6 Atributo array:  
`print(serie22.array)  # <NumpyExtensionArray>`  
                            `# [0, 1, 2, 3, 4]`  
                            `# Length: 5, dtype: int64`

2.2.7 Atributo shape: devuelve una tupla  
`print(serie22.shape)  # tupla (5,)`

In [101]:
# CÓDIGO DE LA SECCIÓN 2.2 SERIES: Atributos

print(f'\n{"="*15} 2.2 SERIES: Atributos')

serie22 = pd.Series(data=[0,1,2,3,4])

print(f'Atributo index: {serie22.index}')  # RangeIndex(start=0, stop=5, step=1)

print(f'Atributo dtype: {serie22.dtype}')  # int64

print(f'Atributo size: {serie22.size}')   # 5

print(f'Atributo ndim: {serie22.ndim}')   # 1

print(f'Atributo values: {serie22.values}') # [0 1 2 3 4]

print(f'Atributo array: {serie22.array}')  # <NumpyExtensionArray>
                                            # [0, 1, 2, 3, 4]
                                            # Length: 5, dtype: int64

print(f'Atributo shape: {serie22.shape}')  # tupla (5,)

=============== 2.2 SERIES: Atributos
Atributo index: RangeIndex(start=0, stop=5, step=1)
Atributo dtype: int64
Atributo size: 5
Atributo ndim: 1
Atributo values: [0 1 2 3 4]
Atributo array: <NumpyExtensionArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64
Atributo shape: (5,)

# 2.3 SERIES: Accesos, conversiones y operaciones

*partiendo de esta serie*

```
serie23 = pd.Series(data=[0,1,2,3,4])
print(serie23.head())
```  

`serie23.head(3)`# Imprime las primeras 3 filas de la serie  
0  
1  
2  


### 2.3.1 Acceso a elementos de la serie usando diferentes métodos

Método at: `print(serie23.at[2]) # 2.0`  
Método loc: `print(serie23.loc[2]) # 2.0`  
Método iloc: `print(serie23.iloc[2]) # 2.0`  
Método keys(): `print(serie23.keys()) # RangeIndex(start=0, stop=5, step=1)`  


### 2.3.2 Conversión

**A) Método astype**

```
serie23 = pd.Series.astype(serie23, dtype=np.float64)
print(serie23) # Imprime la serie convertida a float64
# [0.0, 1.0, 2.0, 3.0, 4.0]
```

**B) Conversión de la serie a lista usando dos métodos diferentes**

```
print(pd.Series.to_list(serie23)) # [0.0, 1.0, 2.0, 3.0, 4.0]
print(serie23.tolist())           # [0.0, 1.0, 2.0, 3.0, 4.0]
```


### 2.3.3 Reemplazar where() y mask()

*Solo se imprime el resultado de where y mask; no se modifica la serie original*  

**A) Reemplazar donde la condición no se cumple**  
Resultado de la serie original después de usar where: reemplaza los valores mayores a 2 por 0.
```
print(serie23.where(serie23 < 2, other=0)) # Reemplaza los valores menores a 2 por 0
```
0---0.0  
1---1.0  
2---0.0  
3---0.0  
4---0.0  

**B) Reemplazar donde la condición se cumple**  
Resultado de la serie original después de usar mask: reemplaza los valores menores a 2 por 5.
```
print(serie23.mask(serie23 < 2, other=5))  # Reemplaza los valores menores a 2 por 5
```
0---5.0  
1---5.0  
2---2.0  
3---3.0  
4---4.0  


### 2.3.4 Operaciones

Se parte de las siguientes series
```
serie234a = pd.Series([0,1,2,3,4])
serie234b = pd.Series([5,6,7,8,9])
```

**A) Operaciones aritméticas entre series: (operaciones elemento a elemento)**

Suma de dos series: `serie234a + serie234b`  
0     5  
1     7  
2     9  
3    11  
4    13  
dtype: int64  

Resta de dos series: `serie234a - serie234b`  
0   -5  
1   -5  
2   -5  
3   -5  
4   -5  
dtype: int64  

Multiplicación de dos series: `serie234a * serie234b`  
0     0  
1     6  
2    14  
3    24  
4    36  
dtype: int64  

División de dos series: `serie234a / serie234b`  
0    0.000000  
1    0.166667  
2    0.285714  
3    0.375000  
4    0.444444  
dtype: float64  


**B) Concatenación de series:**
```
serie234c = pd.concat([serie234a, serie234b])
print(f'Concatenación de las dos series:\n{serie234c}') 
```
Concatenación de las dos series:  
0---0  
1---1  
2---2  
3---3  
4---4  
0---5  
1---6  
2---7  
3---8  
4---9  
dtype: int64  

**C) Métodos estadísticos**  

De vuelta a esta serie:
```
serie23 = pd.Series(data=[0,1,2,3,4])
serie23 = pd.Series.astype(serie23, dtype=np.float64)
```

**idmax()** da el índice del valor máximo: `serie23.idxmax() # 4`  
**idmin()** da el índice del valor mínimo: `serie23.idxmin() # 0`  
**max()** da el valor máximo: `serie23.max() # 4.0`  
**min()** da el valor mínimo: `serie23.min()  # 0.0`  
**sum()** da la suma de los valores: `serie23.sum()  # 10.0`  
**mean()** da el valor promedio: `serie23.mean()  # 2.0`

In [102]:
# CÓDIGO DE LA SECCIÓN 2.3 SERIES: Accesos, conversiones y operaciones

print(f'\n{"="*15} 2.3 SERIES: Accesos, conversiones y operaciones')

serie23 = pd.Series(data=[0,1,2,3,4])
print(f'Serie original: {serie23}') # Imprime la serie original
print(f'\nHead(3): Imprime las primeras 3 filas de la serie\n{serie23.head(3)}') # Imprime las primeras 3 filas de la serie

print("\n2.3.1 Acceso a elementos de la serie usando diferentes métodos:")
print(f'Método at: {serie23.at[2]}')                     # 2.0
print(f'Método loc: {serie23.loc[2]}')                    # 2.0
print(f'Método iloc: {serie23.iloc[2]}')                   # 2.0
print(f'Método keys(): {serie23.keys()}')                # RangeIndex(start=0, stop=5, step=1

print("\n2.3.2 Conversiónes de tipo de datos")
serie23 = pd.Series.astype(serie23, dtype=np.float64)
print(f'A) Serie convertida a float64 con astype(): {serie23}') # Imprime la serie convertida a float64

print(f'\nB) Conversión de la serie a lista usando dos métodos diferentes: lo_list() y tolist()')

print(f'Conversión con to_list(): {pd.Series.to_list(serie23)}')
print(f'Conversión con tolist(): {serie23.tolist()}')                   # [0.0, 1.0, 2.0, 3.0, 4.0]

print("-"*40)

print(f'\n2.3.3 Reemplazar where() y mask()')

print("Ahora solo se imprime el resultado de where y mask; no se modifica la serie original")
# Reemplazar donde la condición NO se cumple
print("\nA) Método where(): reemplaza donde la condición NO se cumple")
print("Resultado de la serie original después de usar where: reemplaza los valores mayores a 2 por 0")
print(serie23.where(serie23 < 2, other=0)) # Reemplaza los valores menores a 2 por 0

# Reemplazar donde la condición SÍ se cumple
print("\nB) Método mask(): reemplaza donde la condición SÍ se cumple")
print("Resultado de la serie original después de usar mask: reemplaza los valores menores a 2 por 5")
print(serie23.mask(serie23 < 2, other=5))  # Reemplaza los valores menores a 2 por 5

print("\n2.3.4 Operaciones con Series")

print("A) Operaciones aritméticas entre series:")
serie234a = pd.Series([0,1,2,3,4])
serie234b = pd.Series([5,6,7,8,9])

print(f'Suma de dos series:\n{serie234a + serie234b}')         # Suma elemento a elemento
print(f'Resta de dos series:\n{serie234a - serie234b}')      # Resta elemento a elemento
print(f'Multiplicación de dos series:\n{serie234a * serie234b}') # Multiplicación elemento a elemento
print(f'División de dos series:\n{serie234a / serie234b}')      # División elemento a elemento

print("\nB) Concatenación de series:")
serie234c = pd.concat([serie234a, serie234b])
print(f'Concatenación de las dos series:\n{serie234c}')

print("\nC) Métodos estadísticos")
print(f'idmax imprime el índice del valor máximo: {serie23.idxmax()}') # 4
print(f'idmin imprime el índice del valor mínimo: {serie23.idxmin()}') # 0
print(f'max imprime el valor máximo: {serie23.max()}') # 4.0
print(f'min imprime el valor mínimo: {serie23.min()}')  # 0.0
print(f'sum imprime la suma de los valores: {serie23.sum()}')  # 10.0
print(f'mean imprime el valor promedio: {serie23.mean()}')  # 2.0

=============== 2.3 SERIES: Accesos, conversiones y operaciones
Serie original: 0    0
1    1
2    2
3    3
4    4
dtype: int64

Head(3): Imprime las primeras 3 filas de la serie
0    0
1    1
2    2
dtype: int64

2.3.1 Acceso a elementos de la serie usando diferentes métodos:
Método at: 2
Método loc: 2
Método iloc: 2
Método keys(): RangeIndex(start=0, stop=5, step=1)

2.3.2 Conversiónes de tipo de datos
A) Serie convertida a float64 con astype(): 0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

B) Conversión de la serie a lista usando dos métodos diferentes: lo_list() y tolist()
Conversión con to_list(): [0.0, 1.0, 2.0, 3.0, 4.0]
Conversión con tolist(): [0.0, 1.0, 2.0, 3.0, 4.0]
----------------------------------------

2.3.3 Reemplazar where() y mask()
Ahora solo se imprime el resultado de where y mask; no se modifica la serie original

A) Método where(): reemplaza donde la condición NO se cumple
Resultado de la serie original después de usar where: reemplaza los valores mayores a 2 por 0
0    0.0
1    1.0
2    0.0
3    0.0
4    0.0
dtype: float64

B) Método mask(): reemplaza donde la condición SÍ se cumple
Resultado de la serie original después de usar mask: reemplaza los valores menores a 2 por 5
0    5.0
1    5.0
2    2.0
3    3.0
4    4.0
dtype: float64

2.3.4 Operaciones con Series
A) Operaciones aritméticas entre series:
Suma de dos series:
0     5
1     7
2     9
3    11
4    13
dtype: int64
Resta de dos series:
0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64
Multiplicación de dos series:
0     0
1     6
2    14
3    24
4    36
dtype: int64
División de dos series:
0    0.000000
1    0.166667
2    0.285714
3    0.375000
4    0.444444
dtype: float64

B) Concatenación de series:
Concatenación de las dos series:
0    0
1    1
2    2
3    3
4    4
0    5
1    6
2    7
3    8
4    9
dtype: int64

C) Métodos estadísticos
idmax imprime el índice del valor máximo: 4
idmin imprime el índice del valor mínimo: 0
max imprime el valor máximo: 4.0
min imprime el valor mínimo: 0.0
sum imprime la suma de los valores: 10.0
mean imprime el valor promedio: 2.0

# 2.4 Series: Fechas

In [103]:
# CÓDIGO DE LA SECCIÓN 2.4 SERIES: Fechas

print(f'\n{"="*15} 2.4 SERIES: Fechas')
serie24 = pd.Series(pd.date_range("20230101", periods=6))
print(serie24)

pd.to_datetime('2023-01-01')  # Timestamp('2023-01-01 00:00:00')

serie1 = pd.Series([1,2,3,4,5])
serie2 = pd.Series([6,7,8,9,10])
print(pd.concat([serie1, serie2]))
print(serie1+serie2)

=============== 2.4 SERIES: Fechas
0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
5   2023-01-06
dtype: datetime64[ns]
0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64
0     7
1     9
2    11
3    13
4    15
dtype: int64


#### 2.X - Prueba para imprimir una Serie en un DataFrame
#### RECORDAR: Series no tiene Display
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
### Sintaxis para DataFrame
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})

In [104]:
# CÓDIGO DE LA SECCIÓN 2.X - Prueba para imprimir una Serie en un DataFrame
print(f'\n{"="*15} 2.X - Prueba para imprimir una Serie en un DataFrame')
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
serie1_prueba 
print(serie1_prueba) # Le pone índice y dtype: object
serie2_prueba = pd.Series(np.random.rand(4))
print(serie2_prueba)
# SINTAXIS DATAFRAME pd.DataFrame ({ "nombre": array})
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})
display(df1_prueba)
df1_prueba.insert( 2, "Nueva columna", np.random.uniform(10,20,4)) # último numero es cuantos genera
df1_prueba.insert( 3, "Otra columna", [10,20,pd.NA,40])
display(df1_prueba)

=============== 2.X - Prueba para imprimir una Serie en un DataFrame
0      Pepe
1      Paco
2    Manolo
3       Ana
Name: Gente, dtype: object
0    0.449051
1    0.540956
2    0.601370
3    0.012162
dtype: float64

   nombre    numero
0    Pepe  0.449051
1    Paco  0.540956
2  Manolo  0.601370
3     Ana  0.012162

   nombre    numero  Nueva columna Otra columna
0    Pepe  0.449051      15.103035           10
1    Paco  0.540956      12.471597           20
2  Manolo  0.601370      13.902269         <NA>
3     Ana  0.012162      15.824689           40