# 02 - Pandas - Series

In [63]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" PANDAS VERSIÓN")
print(pd.__version__) # imprime versión de pandas (sólo números)

=============== PANDAS VERSIÓN
2.3.3

# 2.1 SERIES: Constructor (parámetros del constructor)

### Constructor: pd.Series()

`pd.Series([data, index, dtype, name, copy])`

### 2.1.1 data = UN ARRAY  

```
serie21 = pd.Series([0,1,2,3,4,5])
print(serie21)
```

### 2.1.2 index = UN ARRAY  

`serie21 = pd.Series([0,1,2,3,4,5], index=['a','b','c','d','e','f'])`

### 2.1.3 dtype = Tipo de dato

`serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], dtype=np.int8)`

### 2.1.4 name="un string"

`serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], name='Mi Serie')`

### 2.1.5 copy = Booleano

*copy=True si se debe realizar una copia de los datos en lugar de crear una referencia*

## RECORDAR: Series no tiene Display

In [64]:
# CÓDIGO DE LA SECCIÓN 2.1 SERIES: Constructor

print(f'\n{"="*15} 2.1 SERIES: Constructor')

print("\nA) Imprime una serie con índice por defecto (0,1,2,3,4,5)")
serie21 = pd.Series(data = [0,1,2,3,4,5])
print(serie21) # Imprime una serie con índice por defecto (0,1,2,3,4,5)

print("\nB) Imprime una serie con índice personalizado ('a','b','c','d','e','f')")
serie21 = pd.Series([0,1,2,3,4,5], index=['a','b','c','d','e','f'])
print(serie21) # Imprime una serie con índice personalizado ('a','b','c','d','e','f')

print("\nC) Imprime el Tipo de dato (personalizado) de una serie (np.int8)")
serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], dtype=np.int8)
print(serie21) # imprime la serie con índice numérico
print(f'Tipo de dato de la serie: {serie21.dtype}') # Imprime el Tipo de dato (personalizado) de una serie (np.int8)

print("\nD) Imprime el nombre personalizado de una serie")
serie21 = pd.Series([0,1,2,3,4,5], index=[10,11,12,13,14,15], name='Mi Serie')
print(f'Nombre de la serie: {serie21.name}') # Imprime el nombre personalizado de una serie

print("\nE) Imprime una serie creada a partir de un diccionario")
serie21 = pd.Series({'a':0,'b':1,'c':2,'d':3,'e':4,'f':5})
print(serie21) # Imprime una serie creada a partir de un diccionario

print("\nF) Imprime una serie creada a partir de un array de NumPy")
serie211 = pd.Series(np.array([0,1,2,3,4,5]))
print(serie21) # Imprime una serie creada a partir de un array de NumPy
print(f'Tipo de dato de la serie creada a partir de un array de NumPy: {serie21.dtype}') # Imprime el tipo de dato de la serie

print("\nG) Imprime una serie con un valor escalar repetido: el número 5")
serie21 = pd.Series(5, index=['a','b','c','d','e','f']) # o data=5
print(serie21) # imprime una serie con valor escalar repetido: el número 5

print("\nH) copy=True si se debe realizar una copia de los datos en lugar de crear una referencia")
serie21 = pd.Series(copy=True) # True si se debe realizar una copia de los datos en lugar de crear una referencia

=============== 2.1 SERIES: Constructor

A) Imprime una serie con índice por defecto (0,1,2,3,4,5)
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

B) Imprime una serie con índice personalizado ('a','b','c','d','e','f')
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

C) Imprime el Tipo de dato (personalizado) de una serie (np.int8)
10    0
11    1
12    2
13    3
14    4
15    5
dtype: int8
Tipo de dato de la serie: int8

D) Imprime el nombre personalizado de una serie
Nombre de la serie: Mi Serie

E) Imprime una serie creada a partir de un diccionario
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

F) Imprime una serie creada a partir de un array de NumPy
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64
Tipo de dato de la serie creada a partir de un array de NumPy: int64

G) Imprime una serie con un valor escalar repetido: el número 5
a    5
b    5
c    5
d    5
e    5
f    5
dtype: int64

H) copy=True si se debe realizar una copia de los datos en lugar de crear una referencia

# 2.2 Series: Atributos

`serie22 = pd.Series(data=[0,1,2,3,4])`

2.2.1 Atributo index:  
`print(serie22.index)  # RangeIndex(start=0, stop=5, step=1)`

2.2.2 Atributo dtype: tipo del contenido de la serie  
`print(serie22.dtype)  # int64`

2.2.3 Atributo size: tamaño  
`print(serie22.size)   # 5`

2.2.4 Atributo ndim: dimensiones  
`print(serie22.ndim)   # 1`

2.2.5 Atributo values: valores del array  
`print(serie22.values) # [0 1 2 3 4]`

2.2.6 Atributo array:  
`print(serie22.array)  # <NumpyExtensionArray>`  
                            `# [0, 1, 2, 3, 4]`  
                            `# Length: 5, dtype: int64`

2.2.7 Atributo shape: devuelve una tupla  
`print(serie22.shape)  # tupla (5,)`

In [65]:
# CÓDIGO DE LA SECCIÓN 2.2 SERIES: Atributos

print(f'\n{"="*15} 2.2 SERIES: Atributos')

serie22 = pd.Series(data=[0,1,2,3,4])

print(f'Atributo index: {serie22.index}')  # RangeIndex(start=0, stop=5, step=1)

print(f'Atributo dtype: {serie22.dtype}')  # int64

print(f'Atributo size: {serie22.size}')   # 5

print(f'Atributo ndim: {serie22.ndim}')   # 1

print(f'Atributo values: {serie22.values}') # [0 1 2 3 4]

print(f'Atributo array: {serie22.array}')  # <NumpyExtensionArray>
                                            # [0, 1, 2, 3, 4]
                                            # Length: 5, dtype: int64

print(f'Atributo shape: {serie22.shape}')  # tupla (5,)

=============== 2.2 SERIES: Atributos
Atributo index: RangeIndex(start=0, stop=5, step=1)
Atributo dtype: int64
Atributo size: 5
Atributo ndim: 1
Atributo values: [0 1 2 3 4]
Atributo array: <NumpyExtensionArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64
Atributo shape: (5,)

# 2.3 SERIES: Búsquedas y conversiones

In [ ]:
# CÓDIGO DE LA SECCIÓN 2.3 SERIES: Búsquedas y conversiones

print(f'\n{"="*15} 2.3 SERIES: Búsquedas y conversiones')

# 2.4 Series: Fechas

In [ ]:
# CÓDIGO DE LA SECCIÓN 2.4 SERIES: Fechas

print(f'\n{"="*15} 2.4 SERIES: Fechas')


#### 2.X - Prueba para imprimir una Serie en un DataFrame
#### RECORDAR: Series no tiene Display
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
### Sintaxis para DataFrame
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})

In [ ]:
# CÓDIGO DE LA SECCIÓN 2.X - Prueba para imprimir una Serie en un DataFrame
print(f'\n{"="*15} 2.X - Prueba para imprimir una Serie en un DataFrame')
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
serie1_prueba 
print(serie1_prueba) # Le pone índice y dtype: object
serie2_prueba = pd.Series(np.random.rand(4))
print(serie2_prueba)
# SINTAXIS DATAFRAME pd.DataFrame ({ "nombre": array})
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})
display(df1_prueba)
df1_prueba.insert( 2, "Nueva columna", np.random.uniform(10,20,4)) # último numero es cuantos genera
df1_prueba.insert( 3, "Otra columna", [10,20,pd.NA,40])
display(df1_prueba)

=============== 2.X - Prueba para imprimir una Serie en un DataFrame
0      Pepe
1      Paco
2    Manolo
3       Ana
Name: Gente, dtype: object
0    0.134340
1    0.275381
2    0.868041
3    0.247553
dtype: float64

   nombre    numero
0    Pepe  0.134340
1    Paco  0.275381
2  Manolo  0.868041
3     Ana  0.247553

   nombre    numero  Nueva columna Otra columna
0    Pepe  0.134340      19.586652           10
1    Paco  0.275381      12.805879           20
2  Manolo  0.868041      17.521642         <NA>
3     Ana  0.247553      13.461215           40